#!/usr/bin/env python3
"""Extract the unchanged 8852B descriptor routines, with explicit provenance."""
import hashlib,json,pathlib,re,subprocess,sys
root=pathlib.Path(__file__).resolve().parents[1]
source=pathlib.Path(sys.argv[1]).resolve()
commit='d1fced1b8a741dc9f92b47c69489c24385945f6e'
assert subprocess.check_output(['git','-C',str(source),'rev-parse','HEAD'],text=True).strip()==commit
assert not subprocess.check_output(['git','-C',str(source),'diff','--','core.c','core.h','txrx.h'],text=True)
texts={n:(source/n).read_text() for n in ('core.c','core.h','txrx.h')}
def block(text,start,struct=False):
    p=text.index(start); a=text.index('{',p); depth=1; b=a+1
    while depth:
        depth+=(text[b]=='{')-(text[b]=='}');b+=1
    if struct:b=text.index(';',b)+1
    return text[p:b]
names=['rtw89_build_txwd_body0','rtw89_build_txwd_body2','rtw89_build_txwd_body3','rtw89_build_txwd_info0','rtw89_build_txwd_info1','rtw89_build_txwd_info2','rtw89_build_txwd_info4','rtw89_core_fill_txdesc','rtw89_core_query_rxdesc']
functions=[]
for n in names:
    prefix=('static __le32 ' if n.startswith('rtw89_build') else 'void ')+n+'('
    functions.append(block(texts['core.c'],prefix))
structs=[block(texts['core.h'],'struct '+n+' {',True) for n in ('rtw89_txwd_body','rtw89_txwd_info','rtw89_rx_desc_info','rtw89_rxdesc_short','rtw89_rxdesc_long','rtw89_tx_desc_info')]
used=set(re.findall(r'\b(?:RTW89_TXWD|AX_RXD)_[A-Za-z0-9_]+','\n'.join(functions)))
defines=[]
for line in texts['txrx.h'].splitlines():
    match=re.match(r'#define\s+(\w+)',line)
    if match and match[1] in used:defines.append(line)
assert len(defines)==len(used)
shim='''// SPDX-License-Identifier: BSD-3-Clause
// Copyright(c) 2020 Realtek Corporation
// Generated by tools/import_network_reference.py. Do not hand-edit.
// Original functions and structures preserved; adapter is descriptor-only.
#pragma once
#include <stdint.h>
namespace rtl8852be { namespace reference {
using u8=uint8_t;using u16=uint16_t;using u32=uint32_t;using __le32=uint32_t;
static inline unsigned shift32(uint32_t n){return static_cast<unsigned>(__builtin_ctz(n));}
static inline uint32_t cpu_to_le32(uint32_t n){return n;} // x86_64-only target
static inline uint32_t le32_get_bits(uint32_t n,uint32_t mask){return (n&mask)>>shift32(mask);}
#define BIT(n) (uint32_t(1)<<(n))
#define GENMASK(h,l) ((uint32_t(0xffffffff)>>(31-(h))) & (uint32_t(0xffffffff)<<(l)))
#define FIELD_PREP(mask,n) ((uint32_t(n)<<shift32(mask))&(mask))
#define __packed __attribute__((packed))
// Only chip_id is used by the imported parser. This is not a Linux device shim.
enum { RTL8852B, RTL8852C };
struct rtw89_chip_info { unsigned chip_id; };
struct rtw89_dev { const rtw89_chip_info *chip; };
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-parameter"
#endif
'''
rendered=shim+'\n'.join(defines)+'\n'+'\n\n'.join(structs)+'\n\n'+'\n\n'.join(f.replace('void rtw89_core_','static inline void rtw89_core_',1) for f in functions)+'\n'
rendered+='\n#if defined(__clang__)\n#pragma clang diagnostic pop\n#endif\n'
rendered+='\n'.join('#undef '+n for n in sorted(used|{'BIT','GENMASK','FIELD_PREP','__packed','RTW89_MGMT_HW_SSN_SEL','RTW89_MGMT_HW_SEQ_MODE'}))+'\n} }\n'
dest=root/'src/network/Rtw89DescriptorCore.hpp';dest.parent.mkdir(parents=True,exist_ok=True)
dest.write_text(rendered)
fields=re.findall(r'FIELD_PREP\((RTW89_TXWD_\w+),\s*desc_info->(\w+)\)', '\n'.join(functions))
# Materialize representability checks from the pinned masks, independently of
# descriptor construction. No silently truncated user-supplied parameters.
maskvalues={}
for line in defines:
    n,v=line.split(None,2)[1:]
    v=re.sub(r'GENMASK\((\d+),\s*(\d+)\)',lambda m:str(((1<<(int(m[1])-int(m[2])+1))-1)<<int(m[2])),v)
    v=re.sub(r'BIT\((\d+)\)',lambda m:str(1<<int(m[1])),v)
    maskvalues[n]=int(v.strip())
checks=[]
for mask,field in fields:
    m=maskvalues[mask];maxval=m//(m&-m)
    fieldtype=re.search(r'\b(u8|u16|u32)\s+'+field+r';',structs[-1])
    natural=(1<<int(fieldtype[1][1:]))-1 if fieldtype else 1
    if 1<maxval<natural:checks.append(f'    if (p.{field} > {maxval}u) return false;')
(root/'src/network/DescriptorLimits.inc').write_text('// Generated from pinned rtw89 TXWD masks.\n'+'\n'.join(dict.fromkeys(checks))+'\n')
manifest={'repository':'https://github.com/lwfinger/rtw89','commit':commit,'license':'BSD-3-Clause option of GPL-2.0 OR BSD-3-Clause','functions':names,'files':{n:hashlib.sha256((source/n).read_bytes()).hexdigest() for n in texts},'generated_sha256':hashlib.sha256(dest.read_bytes()).hexdigest()}
(root/'src/network/reference-provenance.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Imported',len(names),'unchanged descriptor functions; not a complete hardware driver.')
