#!/usr/bin/env python3
"""Import exact AX CMAC/CAM setters from the pinned Realtek BSD-option source."""
import hashlib, json, pathlib, re, subprocess, sys
root = pathlib.Path(__file__).resolve().parents[1]
source = pathlib.Path(sys.argv[1]).resolve()
commit = 'd1fced1b8a741dc9f92b47c69489c24385945f6e'
def git(*args): return subprocess.check_output(['git', '-C', str(source), *args])
assert git('rev-parse', 'HEAD').decode().strip() == commit
files = ['fw.h', 'fw.c', 'cam.h', 'cam.c', 'core.h', 'mac.h', 'mac.c', 'reg.h', 'rtw8852b.c']
assert not git('diff', 'HEAD', '--', *files), 'Reference files have local changes'
texts = {name: git('show', 'HEAD:' + name).decode() for name in files}
names = ['SET_CTRL_INFO_MACID', 'SET_CTRL_INFO_OPERATION']
names += ['SET_CMC_TBL_' + x for x in '''TXPWR_MODE NTX_PATH_EN PATH_MAP_A PATH_MAP_B
PATH_MAP_C PATH_MAP_D ANTSEL_A ANTSEL_B ANTSEL_C ANTSEL_D DOPPLER_CTRL TXPWR_TOLERENCE
DISRTSFB DISDATAFB RTS_RTY_LOWEST_RATE RTS_TXCNT_LMT_SEL DATA_TXCNT_LMT_SEL ULDL
MULTI_PORT_ID NOMINAL_PKT_PADDING NOMINAL_PKT_PADDING40 NOMINAL_PKT_PADDING80
NOMINAL_PKT_PADDING160 BSR_QUEUE_SIZE_FORMAT'''.split()]
names += re.findall(r'^static inline void (FWCMD_SET_ADDR_\w+)\(', texts['cam.h'], re.M)
macros = {}
for text in texts.values():
    for name, value in re.findall(r'^#define\s+(\w+)\s+([^\n]+)', text, re.M):
        macros[name] = value.strip()
def value(expr):
    expr = expr.strip()
    if expr in macros: return value(macros[expr])
    m = re.fullmatch(r'BIT\((\d+)\)', expr)
    if m: return 1 << int(m[1])
    m = re.fullmatch(r'GENMASK\((\d+),\s*(\d+)\)', expr)
    if m: return ((1 << (int(m[1]) + 1)) - 1) ^ ((1 << int(m[2])) - 1)
    return int(expr, 0)
lines = ['// SPDX-License-Identifier: BSD-3-Clause',
         '// Copyright(c) 2019-2022 Realtek Corporation (upstream BSD option).',
         '// Generated by tools/import_station_tables_reference.py; do not edit.',
         '#pragma once', 'namespace rtl8852be { namespace station { namespace tables { namespace wire {']
function_hashes = {}
for name in names:
    src = texts['cam.h'] if name.startswith('FWCMD_') else texts['fw.h']
    m = re.search(r'static inline void ' + name + r'\(void \*\w+, u32 \w+\)\n\{[^}]+\}', src)
    assert m, name
    original = m[0]
    function_hashes[name] = hashlib.sha256(original.encode()).hexdigest()
    ops = re.findall(r'le32p_replace_bits\(\(__le32 \*\)\(\w+\) \+ (\d+),\s*(\w+),\s*(BIT\(\d+\)|GENMASK\(\d+,\s*\d+\))\);', original)
    assert ops and len(ops) == original.count('le32p_replace_bits'), name
    lines.append('inline void ' + name + '(uint8_t *out,uint32_t v){')
    for word, argument, mask in ops:
        arg = 'v' if argument in ('val', 'value') else '0x%xU' % value(argument)
        lines.append('    replace(out,%s,%s,0x%08xU);' % (word, arg, value(mask)))
    lines.append('}')
for name in ['R_AX_FILTER_MODEL_ADDR', 'R_AX_INDIR_ACCESS_ENTRY', 'CMAC_TBL_BASE_ADDR',
             'DMAC_TBL_BASE_ADDR', 'CCTL_INFO_SIZE', 'ADDR_CAM_ENT_SIZE', 'BSSID_CAM_ENT_SIZE']:
    lines.append('constexpr uint32_t %s=0x%xU;' % (name, value(name)))
lines += ['} } } }', '']
destination = root / 'src/network/Rtw8852bStationTableFields.hpp'
destination.write_text('\n'.join(lines), encoding='utf-8', newline='\n')
provenance = {
    'source_commit': commit,
    'source_files_sha256': {name: hashlib.sha256(text.encode()).hexdigest() for name, text in texts.items()},
    'setter_source_sha256': function_hashes,
    'setter_count': len(names),
    'adaptation': 'Replace unaligned __le32 pointer operations with byte-safe little-endian replace; preserve field masks and CMAC update masks.',
    'hardware_tested': False,
}
(root / 'src/network/station-tables-reference-provenance.json').write_text(json.dumps(provenance, indent=2, sort_keys=True) + '\n', encoding='utf-8', newline='\n')
print('Imported %d pinned CMAC/CAM setters' % len(names))
