// SPDX-License-Identifier: BSD-3-Clause
// Copyright(c) 2019-2022 Realtek Corporation (upstream BSD option).
// Generated by tools/import_station_tables_reference.py; do not edit.
#pragma once
namespace rtl8852be { namespace station { namespace tables { namespace wire {
inline void SET_CTRL_INFO_MACID(uint8_t *out,uint32_t v){
    replace(out,0,v,0x0000007fU);
}
inline void SET_CTRL_INFO_OPERATION(uint8_t *out,uint32_t v){
    replace(out,0,v,0x00000080U);
}
inline void SET_CMC_TBL_TXPWR_MODE(uint8_t *out,uint32_t v){
    replace(out,5,v,0x00000e00U);
    replace(out,13,0x7U,0x00000e00U);
}
inline void SET_CMC_TBL_NTX_PATH_EN(uint8_t *out,uint32_t v){
    replace(out,6,v,0x000f0000U);
    replace(out,14,0xfU,0x000f0000U);
}
inline void SET_CMC_TBL_PATH_MAP_A(uint8_t *out,uint32_t v){
    replace(out,6,v,0x00300000U);
    replace(out,14,0x3U,0x00300000U);
}
inline void SET_CMC_TBL_PATH_MAP_B(uint8_t *out,uint32_t v){
    replace(out,6,v,0x00c00000U);
    replace(out,14,0x3U,0x00c00000U);
}
inline void SET_CMC_TBL_PATH_MAP_C(uint8_t *out,uint32_t v){
    replace(out,6,v,0x03000000U);
    replace(out,14,0x3U,0x03000000U);
}
inline void SET_CMC_TBL_PATH_MAP_D(uint8_t *out,uint32_t v){
    replace(out,6,v,0x0c000000U);
    replace(out,14,0x3U,0x0c000000U);
}
inline void SET_CMC_TBL_ANTSEL_A(uint8_t *out,uint32_t v){
    replace(out,6,v,0x10000000U);
    replace(out,14,0x1U,0x10000000U);
}
inline void SET_CMC_TBL_ANTSEL_B(uint8_t *out,uint32_t v){
    replace(out,6,v,0x20000000U);
    replace(out,14,0x1U,0x20000000U);
}
inline void SET_CMC_TBL_ANTSEL_C(uint8_t *out,uint32_t v){
    replace(out,6,v,0x40000000U);
    replace(out,14,0x1U,0x40000000U);
}
inline void SET_CMC_TBL_ANTSEL_D(uint8_t *out,uint32_t v){
    replace(out,6,v,0x80000000U);
    replace(out,14,0x1U,0x80000000U);
}
inline void SET_CMC_TBL_DOPPLER_CTRL(uint8_t *out,uint32_t v){
    replace(out,7,v,0x000c0000U);
    replace(out,15,0x3U,0x000c0000U);
}
inline void SET_CMC_TBL_TXPWR_TOLERENCE(uint8_t *out,uint32_t v){
    replace(out,7,v,0x0f000000U);
    replace(out,15,0xfU,0x0f000000U);
}
inline void SET_CMC_TBL_DISRTSFB(uint8_t *out,uint32_t v){
    replace(out,1,v,0x02000000U);
    replace(out,9,0x1U,0x02000000U);
}
inline void SET_CMC_TBL_DISDATAFB(uint8_t *out,uint32_t v){
    replace(out,1,v,0x04000000U);
    replace(out,9,0x1U,0x04000000U);
}
inline void SET_CMC_TBL_RTS_RTY_LOWEST_RATE(uint8_t *out,uint32_t v){
    replace(out,2,v,0xf0000000U);
    replace(out,10,0xfU,0xf0000000U);
}
inline void SET_CMC_TBL_RTS_TXCNT_LMT_SEL(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00000800U);
    replace(out,10,0x1U,0x00000800U);
}
inline void SET_CMC_TBL_DATA_TXCNT_LMT_SEL(uint8_t *out,uint32_t v){
    replace(out,3,v,0x00000040U);
    replace(out,11,0x1U,0x00000040U);
}
inline void SET_CMC_TBL_ULDL(uint8_t *out,uint32_t v){
    replace(out,7,v,0x00020000U);
    replace(out,15,0x1U,0x00020000U);
}
inline void SET_CMC_TBL_MULTI_PORT_ID(uint8_t *out,uint32_t v){
    replace(out,5,v,0x00000007U);
    replace(out,13,0x7U,0x00000007U);
}
inline void SET_CMC_TBL_NOMINAL_PKT_PADDING(uint8_t *out,uint32_t v){
    replace(out,7,v,0x00300000U);
    replace(out,15,0x3U,0x00300000U);
}
inline void SET_CMC_TBL_NOMINAL_PKT_PADDING40(uint8_t *out,uint32_t v){
    replace(out,7,v,0x00c00000U);
    replace(out,15,0x3U,0x00c00000U);
}
inline void SET_CMC_TBL_NOMINAL_PKT_PADDING80(uint8_t *out,uint32_t v){
    replace(out,7,v,0xc0000000U);
    replace(out,15,0x3U,0xc0000000U);
}
inline void SET_CMC_TBL_NOMINAL_PKT_PADDING160(uint8_t *out,uint32_t v){
    replace(out,8,v,0x30000000U);
    replace(out,16,0x3U,0x30000000U);
}
inline void SET_CMC_TBL_BSR_QUEUE_SIZE_FORMAT(uint8_t *out,uint32_t v){
    replace(out,6,v,0x00002000U);
    replace(out,14,0x1U,0x00002000U);
}
inline void FWCMD_SET_ADDR_IDX(uint8_t *out,uint32_t v){
    replace(out,1,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_OFFSET(uint8_t *out,uint32_t v){
    replace(out,1,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_LEN(uint8_t *out,uint32_t v){
    replace(out,1,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_VALID(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00000001U);
}
inline void FWCMD_SET_ADDR_NET_TYPE(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00000006U);
}
inline void FWCMD_SET_ADDR_BCN_HIT_COND(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00000018U);
}
inline void FWCMD_SET_ADDR_HIT_RULE(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00000060U);
}
inline void FWCMD_SET_ADDR_BB_SEL(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00000080U);
}
inline void FWCMD_SET_ADDR_ADDR_MASK(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00003f00U);
}
inline void FWCMD_SET_ADDR_MASK_SEL(uint8_t *out,uint32_t v){
    replace(out,2,v,0x0000c000U);
}
inline void FWCMD_SET_ADDR_SMA_HASH(uint8_t *out,uint32_t v){
    replace(out,2,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_TMA_HASH(uint8_t *out,uint32_t v){
    replace(out,2,v,0xff000000U);
}
inline void FWCMD_SET_ADDR_BSSID_CAM_IDX(uint8_t *out,uint32_t v){
    replace(out,3,v,0x0000003fU);
}
inline void FWCMD_SET_ADDR_SMA0(uint8_t *out,uint32_t v){
    replace(out,4,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_SMA1(uint8_t *out,uint32_t v){
    replace(out,4,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_SMA2(uint8_t *out,uint32_t v){
    replace(out,4,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_SMA3(uint8_t *out,uint32_t v){
    replace(out,4,v,0xff000000U);
}
inline void FWCMD_SET_ADDR_SMA4(uint8_t *out,uint32_t v){
    replace(out,5,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_SMA5(uint8_t *out,uint32_t v){
    replace(out,5,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_TMA0(uint8_t *out,uint32_t v){
    replace(out,5,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_TMA1(uint8_t *out,uint32_t v){
    replace(out,5,v,0xff000000U);
}
inline void FWCMD_SET_ADDR_TMA2(uint8_t *out,uint32_t v){
    replace(out,6,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_TMA3(uint8_t *out,uint32_t v){
    replace(out,6,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_TMA4(uint8_t *out,uint32_t v){
    replace(out,6,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_TMA5(uint8_t *out,uint32_t v){
    replace(out,6,v,0xff000000U);
}
inline void FWCMD_SET_ADDR_MACID(uint8_t *out,uint32_t v){
    replace(out,8,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_PORT_INT(uint8_t *out,uint32_t v){
    replace(out,8,v,0x00000700U);
}
inline void FWCMD_SET_ADDR_TSF_SYNC(uint8_t *out,uint32_t v){
    replace(out,8,v,0x00003800U);
}
inline void FWCMD_SET_ADDR_TF_TRS(uint8_t *out,uint32_t v){
    replace(out,8,v,0x00004000U);
}
inline void FWCMD_SET_ADDR_LSIG_TXOP(uint8_t *out,uint32_t v){
    replace(out,8,v,0x00008000U);
}
inline void FWCMD_SET_ADDR_TGT_IND(uint8_t *out,uint32_t v){
    replace(out,8,v,0x07000000U);
}
inline void FWCMD_SET_ADDR_FRM_TGT_IND(uint8_t *out,uint32_t v){
    replace(out,8,v,0x38000000U);
}
inline void FWCMD_SET_ADDR_AID12(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00000fffU);
}
inline void FWCMD_SET_ADDR_AID12_0(uint8_t *out,uint32_t v){
    replace(out,9,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_AID12_1(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00000f00U);
}
inline void FWCMD_SET_ADDR_WOL_PATTERN(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00001000U);
}
inline void FWCMD_SET_ADDR_WOL_UC(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00002000U);
}
inline void FWCMD_SET_ADDR_WOL_MAGIC(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00004000U);
}
inline void FWCMD_SET_ADDR_WAPI(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00008000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT_MODE(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00030000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT0_KEYID(uint8_t *out,uint32_t v){
    replace(out,9,v,0x000c0000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT1_KEYID(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00300000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT2_KEYID(uint8_t *out,uint32_t v){
    replace(out,9,v,0x00c00000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT3_KEYID(uint8_t *out,uint32_t v){
    replace(out,9,v,0x03000000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT4_KEYID(uint8_t *out,uint32_t v){
    replace(out,9,v,0x0c000000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT5_KEYID(uint8_t *out,uint32_t v){
    replace(out,9,v,0x30000000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT6_KEYID(uint8_t *out,uint32_t v){
    replace(out,9,v,0xc0000000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT_VALID(uint8_t *out,uint32_t v){
    replace(out,10,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_SEC_ENT0(uint8_t *out,uint32_t v){
    replace(out,10,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_SEC_ENT1(uint8_t *out,uint32_t v){
    replace(out,10,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT2(uint8_t *out,uint32_t v){
    replace(out,10,v,0xff000000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT3(uint8_t *out,uint32_t v){
    replace(out,11,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_SEC_ENT4(uint8_t *out,uint32_t v){
    replace(out,11,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_SEC_ENT5(uint8_t *out,uint32_t v){
    replace(out,11,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_SEC_ENT6(uint8_t *out,uint32_t v){
    replace(out,11,v,0xff000000U);
}
inline void FWCMD_SET_ADDR_BSSID_IDX(uint8_t *out,uint32_t v){
    replace(out,12,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_BSSID_OFFSET(uint8_t *out,uint32_t v){
    replace(out,12,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_BSSID_LEN(uint8_t *out,uint32_t v){
    replace(out,12,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_BSSID_VALID(uint8_t *out,uint32_t v){
    replace(out,13,v,0x00000001U);
}
inline void FWCMD_SET_ADDR_BSSID_BB_SEL(uint8_t *out,uint32_t v){
    replace(out,13,v,0x00000002U);
}
inline void FWCMD_SET_ADDR_BSSID_MASK(uint8_t *out,uint32_t v){
    replace(out,13,v,0x000000fcU);
}
inline void FWCMD_SET_ADDR_BSSID_BSS_COLOR(uint8_t *out,uint32_t v){
    replace(out,13,v,0x00003f00U);
}
inline void FWCMD_SET_ADDR_BSSID_BSSID0(uint8_t *out,uint32_t v){
    replace(out,13,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_BSSID_BSSID1(uint8_t *out,uint32_t v){
    replace(out,13,v,0xff000000U);
}
inline void FWCMD_SET_ADDR_BSSID_BSSID2(uint8_t *out,uint32_t v){
    replace(out,14,v,0x000000ffU);
}
inline void FWCMD_SET_ADDR_BSSID_BSSID3(uint8_t *out,uint32_t v){
    replace(out,14,v,0x0000ff00U);
}
inline void FWCMD_SET_ADDR_BSSID_BSSID4(uint8_t *out,uint32_t v){
    replace(out,14,v,0x00ff0000U);
}
inline void FWCMD_SET_ADDR_BSSID_BSSID5(uint8_t *out,uint32_t v){
    replace(out,14,v,0xff000000U);
}
constexpr uint32_t R_AX_FILTER_MODEL_ADDR=0xc04U;
constexpr uint32_t R_AX_INDIR_ACCESS_ENTRY=0x40000U;
constexpr uint32_t CMAC_TBL_BASE_ADDR=0x18840000U;
constexpr uint32_t DMAC_TBL_BASE_ADDR=0x18800000U;
constexpr uint32_t CCTL_INFO_SIZE=0x20U;
constexpr uint32_t ADDR_CAM_ENT_SIZE=0x40U;
constexpr uint32_t BSSID_CAM_ENT_SIZE=0x8U;
} } } }
